### ISSUE TITLE
fix on save

### ISSUE THREAD

**Issue by bennypowers** [AtomLinter/linter-jsonlint#122]
It would be lovely if this package would fix simple errors (trailing comma, for example) on save.

Thank you for publishing this useful package.

**Comment by Arcanemagus** [comment]
This package is a wrapper around [jsonlint](https://github.com/zaach/jsonlint), bringing its results inside of Atom, you'll want to file an issue there about getting support added for fixing the files.

Note that `jsonlint` development appears to be halted, so you will probably be better off using a different tool such as [ESLint](https://eslint.org/) or [Prettier](https://prettier.io/) on your JSON.
