### ISSUE TITLE
Add Shogo (1000ch) as a maintainer

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-jsonlint#21]
Shogo (@1000ch) has upgraded this package to the latest API and has been sending PRs every since whenever necessary. He's already a member of the org and maintains [linter-stylelint](https://github.com/atomlinter/linter-stylelint).
He has shown interest in maintaining this repo. He has my vote :+1: 
What do you think?
/cc @AtomLinter/owners

**Comment by steelbrain** [comment]
@1000ch You're in!

**Comment by 1000ch** [comment]
:+1:
