### ISSUE TITLE
Making errors selectable

### ISSUE THREAD

**Issue by alexhudici** [AtomLinter/linter-jsonlint#55]
At the moment there is no easy way to copy the error output in Atom. 

The inline tooltip does not let the user select the error text and the console at the bottom of the Atom window minifies when the mouse is unclicked after selecting the text.

**Comment by Arcanemagus** [comment]
This package only provides messages, `Linter` is the package that provides the interface you see. That being said, all of that is already fixed in the UI rewrite happening [here](https://github.com/steelbrain/linter-ui-default).

**Comment by alexhudici** [comment]
awesome, ty!
