### ISSUE TITLE
Ignore comments in JSON file

### ISSUE THREAD

**Issue by rkpatel33** [AtomLinter/linter-jsonlint#73]
Is there any way to set this up to ignore comments in a JSON file? I strip them out when I load them but keep them in long files for documentation purposes.

![image](https://cloud.githubusercontent.com/assets/3799489/23003785/e054cc84-f3a7-11e6-9764-6beaeec572ca.png)

**Comment by Arcanemagus** [comment]
There is no such thing as comments in a JSON file, there are variants that allow it such as cJSON, but I'm pretty sure that `jsonlint` can't validate cJSON.

**Comment by wordofchristian** [comment]
Comments are supported by [json5](http://json5.org/) which is already supported for configuring popular tools such as [babel](http://babeljs.io/docs/usage/babelrc/#top).

I'm wondering if a separate issue should be created to support JSON5?

**Comment by Arcanemagus** [comment]
That's cool, although I imagine adding support for that will make parsers more complex.

You should file an issue on [jsonlint](https://github.com/zaach/jsonlint) about it, as this project is just a simple wrapper around that allowing it to run in the Atom Linter ecosystem.

**Comment by RandyKnapp** [comment]
At lines 409, 496 of the loottables.json you're missing commas. For future issues of this type, note that I will close the bug. You are responsible for properly formatting your json files, my apologies, but I just don't have the time.
