### ISSUE TITLE
Atom IDE support

### ISSUE THREAD

**Issue by tillkruss** [AtomLinter/linter-jsonlint#83]
Are there any plans for adding Atom IDE support (diagnostics)? I can't use Atom IDE diagnostics with linter.

**Comment by Arcanemagus** [comment]
`atom-ide-ui` uses the `linter` API for "diagnostics", as such it already supports running all `linter-*` providers.

**Comment by tillkruss** [comment]
Ah okay. Thanks. Atom was asking me to install linter, that's why I asked.

**Comment by Arcanemagus** [comment]
Ah, unfortunately Atom doesn't have service _requirements_, so that's a workaround so users have something usable. You can leave `linter` disabled if you prefer `atom-ide-ui`'s interface.
