### ISSUE TITLE
Not linting git-ignored files

### ISSUE THREAD

**Issue by gabmontes** [AtomLinter/linter-jsonlint#85]
Possibly related to #75 , my case is the opposite. I have git-ignored JSON configuration files that I wish to be linted and see errors in Atom but will never be comitted. Perhaps an option to enable/disable linting git-ignored files would be great.

**Comment by Arcanemagus** [comment]
`linter` respects Atom's global "Exclude VCS Ignored Paths", if you _really_ want this just disable that option under Settings -> Core.

_Configuration files generally should be committed to your repo, especially if they are important enough that you want them linted._
